### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by SuperDaYuanYuan** [vanilladb/vanillacore#101]
![微信图片_20221109211053](https://user-images.githubusercontent.com/36960542/200839335-3b70e473-3275-45ab-baad-79bf6778f38d.jpg)

Hello. I try to join A and B in an implicit way. But why do I got this?

**Comment by wilbertharriman** [comment]
Thanks for pointing out this abnormality. 
We found that this is caused by our HeuristicQueryPlanner.

Expect fix very soon. 
In the meantime, you can use our BasicQueryPlanner to avoid this abnormality.

**Comment by wilbertharriman** [comment]
Hi, this issue is caused by MultiBufferProductScan that starts record scanning at the header page.
We have successfully resolved this issue and opened a PR.

Thanks for your help and let us know if you would like to contribute!
