### ISSUE TITLE
Droping corresponding indexes and views while during the owner table

### ISSUE THREAD

**Issue by SLMT** [vanilladb/vanillacore#19]
When a user drops a table, VanillaCore should drop the corresponding indexes and views.

This can be broken down into two separate jobs. One it to drop indexes, another is to drop views.

**Comment by kyechou** [comment]
In order to drop corresponding views, it has to search for the viewDefs that access the table.
I wonder whether it is okay to add a function in ViewMgr.java:
`Collection<String> getViewNameByTable(String tblName, Transaction tx)`
