### ISSUE TITLE
maven build test error and cannot start db in osx

### ISSUE THREAD

**Issue by sj82516** [vanilladb/vanillacore#25]
### Env:
osx: 10.12
Apache Maven 3.5.0 
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### What I did:
clone vaillacore@0.2.2 and run 
`mvn package` , it threw some error
"org.vanilladb.core.storage.tx.concurrency.ConcurrencyTest  Time elapsed: 0.179 sec  <<< ERROR!
java.lang.OutOfMemoryError: unable to create new native thread
"
then I tried 
`mvn package -Dmaven.test.skip=true` It build the target and .jar file.

Run
`java -classpath core-0.2.2.jar org.vanilladb.core.server.StartUp  test`
It throw `Exception in thread "main" java.lang.RuntimeException: cannot access .....`
But I check my file dir and the `test` folder was created under the project folder which path is defined inside the properties file.

### What I expected to see:
successfully run `mvn package` and run vanillacore server.

**Comment by SLMT** [comment]
Thanks for your report. We just found the problem.

Because our `BufferPoolConcurrencyTest` intends to create 10000 native threads during testing and OSX usually does not allow so many threads for a process, the testing process fails to create new thread.

We will upload a quick patch soon.

**Comment by SLMT** [comment]
#26 should fix your first problem.

Could you try it again ?

**Comment by sj82516** [comment]
it works now.
Thanks

**Comment by SLMT** [comment]
Great !
BTW, does the second problem still exist ?

**Comment by sj82516** [comment]
Yes it works now.
But it seems that I cannot name my db as "test" nor it would throw 
```
>  java -classpath core-0.2.2.jar org.vanilladb.core.server.StartUp test 
.....
recovering existing database
Exception in thread "main" java.lang.NullPointerException
```

I changed "test" to "test1" then worked.

Thanks, please close this issue.

**Comment by SLMT** [comment]
Thanks for your information. We will keep eyes on it.
